on: [pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install starlark
        run: cd /home/runner/go/src/ && go get starlark.net
      - name: Go test
        run: go test ./...
      - name: Build some directly
        run: make seed_run simple_run
      - name: bramblescripts
        run: make bramblescripts_to_test
