on: [pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install protoc
        run: |
          set -ex
          sudo apt-get update
          sudo apt install -y protobuf-compiler
          go get -u github.com/golang/protobuf/protoc-gen-go
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run all tests
        run: make test
